[features]
seeds = false
[programs.mainnet]
swap_program = "4hfUykhqmD7ZRvNh1HuzVKEY7ToENixtdUKZspNDCrEM"
[programs.localnet]
swap_program = "4hfUykhqmD7ZRvNh1HuzVKEY7ToENixtdUKZspNDCrEM"
[programs.devnet]
swap_program = "4hfUykhqmD7ZRvNh1HuzVKEY7ToENixtdUKZspNDCrEM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/mainnet.key"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/instructions/*.ts"
