[features]
seeds = false

[programs.mainnet]
swap_program = "8YiqJKjuS7zKPYoxdMFsfPpavPYCnu13Yx1CFqgV6o43"

[programs.localnet]
swap_program = "8YiqJKjuS7zKPYoxdMFsfPpavPYCnu13Yx1CFqgV6o43"

[programs.devnet]
swap_program = "8YiqJKjuS7zKPYoxdMFsfPpavPYCnu13Yx1CFqgV6o43"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/mainnet.key"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/instructions/deposit.ts"
